# @TODO need to test pushing to camden repo / will need to setup tokens

name: Deploy to Camden Netlify Staging

on:
  repository_dispatch:
    types: [code_update_staging]

jobs:
  handle-event:
    runs-on: ubuntu-latest
    environment: staging - camden

    steps:
      - name: Handle repository dispatch event
        run: |
          echo "Received repository dispatch event"
          echo "${{ github.event.client_payload.description }}"

      - name: Checkout DSN code
        run: |
          # https://stackoverflow.com/a/69979203
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name "Council Digital Site Notice Deployment Bot"
          git config --global user.email "${{secrets.CAMDEN_GITHUB_DEPLOY_EMAIL}}"
          git clone https://github.com/tpximpact/council-digital-site-notice .
          git checkout DSNPI-45-sort-hosting-out-for-lambeth-dsn
          ls -lah

      - name: Deploy to repo
        env:
          TOKEN: ${{ secrets.CAMDEN_GITHUB_DEPLOY_TOKEN }}
        run: |
          git remote add camden-dsn https://x-access-token:${TOKEN}@github.com/tpximpact/camden-digital-site-notice.git
          git push camden-dsn DSNPI-45-sort-hosting-out-for-lambeth-dsn:staging
