name: Deploy to Lambeth Heroku Staging
on:
  push:
    branches:
      - deploy-heroku

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Checkout DSN code
        run: |
          git submodule add https://github.com/tpximpact/council-digital-site-notice
          ls -lah council-digital-site-notice
          cd council-digital-site-notice
          git checkout main
          ls -lah
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
      - name: Checkout DSN code
        run: |
          git submodule add https://github.com/tpximpact/council-digital-site-notice
          ls -lah council-digital-site-notice
          cd council-digital-site-notice
          git checkout main
          ls -lah
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.LAMBETH_HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.LAMBETH_HEROKU_EMAIL }}
          HEROKU_APP_NAME: ${{ secrets.LAMBETH_HEROKU_APP_NAME }}
        run: heroku login -i
      - name: Add Heroku remote
        env:
          HEROKU_APP_NAME: ${{ secrets.LAMBETH_HEROKU_APP_NAME }}
        run: heroku git:remote -a $HEROKU_APP_NAME
      - name: Deploy to Heroku
        run: git push heroku deploy-heroku:main
      - name: Ensure Heroku app is up
        env:
          HEROKU_APP_NAME: ${{ secrets.LAMBETH_HEROKU_APP_NAME }}
        run: heroku ps:scale web=1 -a $HEROKU_APP_NAME
