name: Deploy to Camden Netlify Production

# on:
#   repository_dispatch:
#     types: [code_update]

jobs:
  handle-event:
    runs-on: ubuntu-latest

    steps:
      - name: Handle repository dispatch event
        run: |
          echo "Received repository dispatch event"
          echo "${{ github.event.client_payload.description }}"

      - name: Checkout DSN code
        run: |
          git clone https://github.com/tpximpact/council-digital-site-notice .

      - name: Deploy to repo
        id: netlify_deploy
        run: |
          git remote add camden-dsn git@github.com:tpximpact/camden-digital-site-notice.git

# git push camden-dsn main
