name: Deploy to Camden Heroku Staging

on:
  repository_dispatch:
    types: [code_update_staging]

jobs:
  handle-event:
    runs-on: ubuntu-latest
    environment: staging - camden

    steps:
      - name: Handle repository dispatch event
        run: |
          echo "Received repository dispatch event"
          echo "${{ github.event.client_payload.description }}"

      - name: Checkout DSN code
        run: |
          git clone https://github.com/tpximpact/council-digital-site-notice .
          git switch staging
          git status
          ls -lah

      - name: Create heroku.yml
        run: |
          echo 'build:' > heroku.yml
          echo '  docker:' >> heroku.yml
          echo '    web: Dockerfile' >> heroku.yml
          echo '  config:' >> heroku.yml
          echo '    NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}' >> heroku.yml
          echo '    NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}' >> heroku.yml
          echo 'run:' >> heroku.yml
          echo '  web: yarn start' >> heroku.yml
          git config user.name "Heroku-Deploy"
          git config user.email "${{ secrets.HEROKU_EMAIL }}"
          git add 'heroku.yml'
          git commit -m 'heroku.yml' --no-verify
          ls -lah

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          stack: "container"
          dontuseforce: 1
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          # Sanity CMS
          HD_NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          HD_SANITY_SECRET_TOKEN: ${{ secrets.SANITY_SECRET_TOKEN }}
          HD_NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          # SANITY STUDIO
          HD_NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          # COMMENTS & FEEDBACK
          HD_NEXT_PUBLIC_SPREADSHEET_ID: ${{ secrets.NEXT_PUBLIC_SPREADSHEET_ID }}
          HD_GOOGLE_SERVICE_CLIENT_EMAIL: ${{ secrets.GOOGLE_SERVICE_CLIENT_EMAIL }}
          HD_GOOGLE_SERVICE_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY }}
          # EMAILS
          HD_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          HD_FEEDBACK_TO_EMAIL: ${{ secrets.FEEDBACK_TO_EMAIL }}
          HD_FEEDBACK_FROM_EMAIL: ${{ secrets.FEEDBACK_FROM_EMAIL }}
