name: Deploy to Camden Netlify Staging

on:
  repository_dispatch:
    types: [code_update_staging]

jobs:
  handle-event:
    runs-on: ubuntu-latest
    environment: staging - camden

    steps:
      - name: Handle repository dispatch event
        run: |
          echo "Received repository dispatch event"
          echo "${{ github.event.client_payload.description }}"

      - name: Checkout DSN code
        run: |
          git clone https://github.com/tpximpact/council-digital-site-notice .
          git checkout staging
          ls -lah

      - name: Setup git config
        run: |
          git config --global user.name "Council Digital Site Notice Deployment Bot"
          git config --global user.email "${{secrets.CAMDEN_GITHUB_DEPLOY_EMAIL}}"

      # https://stackoverflow.com/a/69979203
      - name: Unset extraheader if exists
        run: |
          git config --get-all http.https://github.com/.extraheader && git config --unset-all http.https://github.com/.extraheader || echo "No extraheader to unset"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CAMDEN_GITHUB_DEPLOY_TOKEN }}

      - name: Add remote repo
        run: |
          git remote add camden-dsn git@github.com:tpximpact/camden-digital-site-notice.git

      - name: Deploy to repo
        run: |
          git push camden-dsn staging
