# NB access token expires 1/1/2025

name: Deploy to Camden Netlify

on:
  repository_dispatch:
    types: [code_update]

jobs:
  handle-event:
    runs-on: ubuntu-latest

    steps:
      - name: Handle repository dispatch event
        run: |
          echo "Received repository dispatch event"
          echo "${{ github.event.client_payload.description }}"

      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Checkout DSN code
        run: |
          git submodule add https://github.com/tpximpact/council-digital-site-notice
          ls -lah council-digital-site-notice
          cd council-digital-site-notice
          git checkout DSNPI-45-sort-hosting-out-for-lambeth-dsn

      - name: Install dependencies
        run: |
          cd council-digital-site-notice
          yarn --frozen-lockfile

      - name: Build project
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.CAMDEN_NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.CAMDEN_NEXT_PUBLIC_SANITY_DATASET }}
        run: |
          cd council-digital-site-notice
          yarn build
          cd ..
          mkdir -p app
          rsync -a ./council-digital-site-notice/public/ ./app/public/
          rsync -a ./council-digital-site-notice/.next/standalone/ ./app/
          rsync -a ./council-digital-site-notice/.next/static/ ./app/.next/static/

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          ls -lah
          ls -lah app
          # @TODO need to authorise this each time
          # netlify link --id ${{ secrets.CAMDEN_NETLIFY_SITE_ID }}
          # netlify env:set NEXT_PUBLIC_SANITY_PROJECT_ID ${{ secrets.CAMDEN_NEXT_PUBLIC_SANITY_PROJECT_ID }}
          # netlify env:set NEXT_PUBLIC_SANITY_DATASET ${{ secrets.CAMDEN_NEXT_PUBLIC_SANITY_DATASET }}

          cd app
          BRANCH_NAME=$(git symbolic-ref --short HEAD)
          prod_flag=""
          if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
          netlify deploy \
            --site ${{ secrets.CAMDEN_NETLIFY_SITE_ID }} \
            --auth ${{ secrets.CAMDEN_NETLIFY_API_TOKEN }} \
            $prod_flag
