name: "Release: staging"

on:
  push:
    tags: ["staging-v*.*.*"]

jobs:
  send-event:
    runs-on: ubuntu-latest

    steps:
      - name: Send staging repository dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/tpximpact/council-digital-site-notice--deployment/dispatches \
            -d '{"event_type":"code_update_staging","client_payload":{"description":"staging branch has been updated"}}'
