name: Send Repository Dispatch Event

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  send-event:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/tpximpact/council-digital-site-notice--deployment/dispatches \
            -d '{"event_type":"custom_event","client_payload":{"custom_field":"custom_value"}}'
